name: Build SuperTokens JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew jar --warning-mode all --no-daemon

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: supertokens-jar
          path: core/build/libs/supertokens.jar
